networks:
  opensearch-net:

services:
  dashboard:
    image: opensearchproject/opensearch-dashboards:2.16.0
    container_name: telegram-dashboard
    ports:
      - ${DASHBOARD_PORT}:5601/tcp
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net
    mem_swappiness: 0

  opensearch:
    image: opensearchproject/opensearch:2.16.0
    container_name: telegram-opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - ${OPENSEARCH_PORT}:9200/tcp
    networks:
      - opensearch-net
    mem_swappiness: 0
