[project]
name = "telegram-listener"
version = "0.1.0"
description = "Just a simple program to save all your messages in Telegram."
authors = [
    {name = "Khiem Doan", email = "doankhiem.crazy@gmail.com"},
]

readme = "README.md"
license = {text = "MIT"}

requires-python = ">=3.12"

dependencies = [
    "tzdata==2025.2",
    "Telethon==1.40.0",
    "loguru==0.7.3",
    "fast-depends==2.4.12",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",
    "opensearch-py[async]==3.0.0",
]

[dependency-groups]
tools = [
]
testing = [
    "pytest",
    "pytest-asyncio",
]
linting = [
    "isort",
    "ruff",
]

[tool.isort]
line_length = 120

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
indent-style = "space"